name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-n-push-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag web-app:$(date +%s)
  

    - name: Login, Tag & Publish Image to DockerHub
      uses: dinushchathurya/build-tag-push-action@v1.2.1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: .
        file: Dockerfile
        repoOwner: ${{ secrets.DOCKER_USERNAME }}
        repository: repo1
        tag: web-app

    - name: image built and published 
      run: echo "image built and published"
      shell: bash 
